apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nirmata-kube-controller
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/anuddeeph1/onboard-n4k-argo.git
    targetRevision: main
    path: nirmata-kube-controller
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: nirmata
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
