# # Default values for nirmata-kube-controller.
# # This is a YAML-formatted file.
# # Declare variables to be passed into your templates.

# Specifies the WebSocket URL for connecting to the Nirmata service.
nirmataURL: "wss://nirmata.io/tunnels"

# Defines the Kubernetes namespace where the Nirmata components will be deployed.
namespace: "nirmata"

#  Contains global configuration settings that is applied across different components.
global:
  # The container registry from which images will be pulled.
  # Replace with your desired container registry.
  imageRegistry: 844333597536.dkr.ecr.us-west-1.amazonaws.com
  # The repository from which images will be pulled.
  # Replace with your desired container repository.
  imageRepository: nirmata
  # Credentials for the private container registry (if required).
  registryUserName: AWS
  registryPassword: eyJwYXlsb2FkIjoiT1orWU9yMEIrem4vWDU1Y0dPeW4xdlFQSDFYc1NkN3g5YklieXlES0J2TEZUVDAvSUs5Z2ZyYXRjOXdzZEZ5STNFWTRmblhSU0dDTHJDNENrMHpJd1N0dkxxb0VGb0Z3aWVpaUxSUVZ4d2xtWmhHcmRKVEdka0lWVmdrMGxhN2lpVzBjQ3BGd1RydUtaWFFBOHJ6SjJHY1lXcURRRnpGb2kyVzZObDljSjd2dEhyTU91b3lNd25UOUJFY3VrZ2VGYnpaNndiVU11dSt1aEwwb2dNWW5WQjBENmZFYnlGbmk4TTROSWJkeURBVnlwZ0Nvc2tLNnNtOUpFcVB1eVBsTUtBOVBUbkF6dkxFTmdRdHhXRlhINUx5WHVlb2ZwaXNlTkw5RGNTQ0J0TlNXb1J2ZjRVUHd0aVEyQkhMaTY1bmZGV3UvWEdGZUZKT2RuUDBJSGIxTlFGTW55Yi8vTUE1TkMxM3JicVVNMy9yQ2F3cTNBYkdXUVpEOW5wQW9VOEI0SmUyNHIwZ3MxR2xZcjBySWd0dXM2aGZRVEZneUljZkJaYjAyeWVBS21ybDdIa0xJMHpIQnhxZUZjZHkzNE44MUs0YzR4bXdGMHVhTkVIM1E1T2hvb2R6cnNFdlRlRkU2RlNMczVmaGRTeGptem9TcXVGbnJDNmVRQVJpVDRJMDIyTEhleTBxaXkrQU5zSDBFenN6SlJWd2JIM0tEMHVSS0dEbEU0SmR2Si9lQWczWEw3dWROdTNYZDJHb1hkcmgyaHR1VVdIcUV4dFB2Sml6NndJS1hTN2hqZDduREZ5UExFM3k1ak02cEYwS3FZVHVRL3E2WStYaWpmY1pORml3Z3lMNWVhNUgxQVpuZzk5SSs4ZlIzQWVmQkNWaVF5U1JPVGxac0d1M2I3anJtVHVPVTdPVFp6cW0zNDBCUEc3UFlSajdIRkpTbGxKdFIyalRqTzNtaGZoTzdaSW03U2RnN3VTbmdid1BwZEJPRTVHeE55UjhzTjBadUZSbE12TTN4aU9VQW5BY1dFRk5BZ2RNcVpsNGpaamhpZVZYRU9Za25kWnVJdjlDSEU2d2VWRHdCRHNsQlQ3eW9naGdiR3dMSjhwdXB1OERzbTFLTGNKVVozcGxrbS9lTnlmZVFKL0YrWDJNQnpPNlRNNS9NZGdPcngvODhybXViY3FxcHVpNmFadWE2SGh3Zkh3SnJUa1FvejM5THBMaXErcDZuNmtDQit3elJjMTA5U1BYNjFjZVM4UEZFcXlmZVo5S0JnOFdaUnhWMUpkVCtONExZbVE3RHNVSkV6WGwwdWg2d0VDeUF6QmtGa2ZYVW9ra2ZvZFg4VVNLa3VxRTdTRGxoIiwiZGF0YWtleSI6IkFRRUJBSGlqRUZYR3dGMWNpcFZPYWNHOHFSbUpvVkJQYXk4TFVVdlU4UkNWVjBYb0h3QUFBSDR3ZkFZSktvWklodmNOQVFjR29HOHdiUUlCQURCb0Jna3Foa2lHOXcwQkJ3RXdIZ1lKWUlaSUFXVURCQUV1TUJFRURNSDk3MVpid0xrVU01K0JTUUlCRUlBN1JHVHE2YXphNjFCc3M0OTVxcHdjWU1hVTQrME1jbFF0WVlNN2hlQ2g1VmlOYXRjL3lCTU5tTWVHcEpnb2JlZWZIcGZkUGhudHFsOTZOWHM9IiwidmVyc2lvbiI6IjIiLCJ0eXBlIjoiREFUQV9LRVkiLCJleHBpcmF0aW9uIjoxNzQ4MDQwNDkwfQ==
  imagePullSecretName: nirmata-controller-registry-secret

# otelAgent contains configuration for the nirmata otel agent, which is used for observability and monitoring.
otelAgent:
  # imageTag is the tag or version of the otel-agent image.
  imageTag: "0.92.0"
  resources:
    requests:
      cpu: 100m
      memory: 200Mi
    limits:
      cpu: 500m
      memory: 1024Mi

# kubeController contains configuration for the nirmata-kube-controller.
kubeController:
  # imageTag is the tag or version of the nirmata-kube-controller image. If added, it will override the  .Chart.AppVersion
  imageTag: ""
  # customCACert contains the custom CA certificate data in base64 encoded format
  customCACert: ""
  # customCaConfigMap specifies an existing ConfigMap containing CA certificate. If provided, this will be used instead of creating a new ConfigMap from customCACert
  customCaConfigMap: ""
  # insecure enables insecure communication with the Nirmata service (skips TLS verification)
  insecure: false
  resources:
    requests:
      cpu: 250m
      memory: 200Mi
    limits:
      cpu: 500m
      memory: 2Gi

# cluster contains configuration related to the Kubernetes cluster which is being onboarded to NCH.
cluster:
  # name used for cluster by nch (Default: kubesystem namespace ID)
  name: "onboarding-using-argo"
  # type of the cluster categorised by nch. (Default value is "default-policy-manager-type")
  type: default-policy-manager-type
  # labels is a set of key-value pairs that can be used to label the cluster while onboarding the cluster to Nirmata Control Hub.
  # These labels are passed as command-line arguments to the Nirmata Kubernetes controller in the deployment.
  # Example:
  # labels:
  #   key1: value1
  #   key2: value2
  #
  # When set, the labels are reflected in the Helm template as follows:
  # In the `deployment.yaml`:
  #       - "-cluster-labels"
  #       - "key1:value1"
  #       - "-cluster-labels"
  #       - "key2:value2"
  labels: {}

# api token is just for registering the cluster to Nirmata Control Hub.
# This token is required for the nirmata-kube-controller to communicate with the Nirmata Control Hub. (Required)
apiToken: "rc9YiREZ5gphOlYH7D8E41hun08y7N5xOpBr9ZGv0vhIecri14GqCptT+nm+nHiUYQG5FBGoSxYehLadJ2Tu1Q=="

# apiTokenSecret is the name of the secret containing the API token.
apiTokenSecret: "nirmata-api-token"

# features enables or disables specific features while installing kube-controller.
# features:
#   policyExceptions:
#     enabled: true
#   policySets:
#     enabled: true

# readWriteMode determines whether the nirmata-kube-controller operates in read-write mode or read-only mode.
# When set to `true`, the controller can make changes to the CR. When `false`, it operates in a read-only manner.
readWriteMode: true

# proxy contains configuration for proxy settings if the KubeController needs to communicate through a proxy.
proxy:
 # httpProxy is the HTTP proxy URL.
  httpProxy: ""
 # httpsProxy is the HTTPS proxy URL.
  httpsProxy: ""
 # noProxy is a comma-separated list of domains or IP addresses that should bypass the proxy.
  noProxy: ""
