apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reports-server
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/anuddeeph1/onboard-n4k-argo.git
    targetRevision: rc-reports-server
    path: reports-server
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
      - DisableOpenAPIValidation=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: apiregistration.k8s.io
      kind: APIService
      name: v1.reports.kyverno.io
    - group: apiregistration.k8s.io
      kind: APIService
      name: v1alpha2.wgpolicyk8s.io
    - group: apps
      kind: StatefulSet
      name: etcd
      namespace: kyverno
    - group: batch
      kind: Job
      namespace: kyverno
      name: reports-server-post-install-install-api-services
